### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by njorocs**
## Requirements
- [ ] This PR has a title that briefly describes the work done including a [conventional commit](https://o3-dev.docs.openmrs.org/#/getting_started/contributing?id=your-pr-title-should-indicate-the-type-of-change-it-is) type prefix and a Jira ticket number if applicable. See existing PR titles for inspiration.

#### For changes to apps
- [ ]  My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide) and [**design documentation**](https://zeroheight.com/23a080e38/p/880723-introduction).

#### If applicable
- [ ] My work includes tests or is validated by existing tests.

## Summary
Code cleanup to prevent crashing slots from other apps. Removed duplicated functionality for lauching post procedure form in referred orders.

### CODE REVIEW

**Comment by jecihjoy** [comment]
@njorocs please attach a video if the UI has changed, also did you manage to look into mutate as we had earlier discussed?

**Comment by njorocs** [comment]
> @njorocs please attach a video if the UI has changed, also did you manage to look into mutate as we had earlier discussed?

I am looking at mutation

**Comment by njorocs** [comment]
> @njorocs please attach a video if the UI has changed, also did you manage to look into mutate as we had earlier discussed?

UI

**Comment by ojwanganto** [comment]
Thanks @njorocs and @jecihjoy. I find the post procedure form button too big. I think the icon looked better to me, not because the button is not good but just considering the responsiveness and the multiple client devices we would want to support

**Pull request merged**
